AWSTemplateFormatVersion: 2010-09-09
Description: Template para Infraestructura II clase 4
Resources:
  Produccion:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1a
      DisableApiTermination: false
      ImageId: ami-0866a3c8686eaeeba
      InstanceType: t2.micro
      InstanceInitiatedShutdownBehavior: stop
      KeyName: infra2
      Monitoring: false
  Testing:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1b
      DisableApiTermination: false
      ImageId: ami-0866a3c8686eaeeba
      InstanceType: t2.micro
      InstanceInitiatedShutdownBehavior: stop
      KeyName: infra2
      Monitoring: false
  Desarrollo:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-east-1c
      DisableApiTermination: false
      ImageId: ami-0324a83b82023f0b3
      InstanceType: t1.micro
      InstanceInitiatedShutdownBehavior: stop
      KeyName: infra2
      Monitoring: false